import { tv } from 'tailwind-variants';

export const styles = tv(
  {
    slots: {
      icon: 'absolute inset-0 m-auto',
      base: 'animate-[spin_0.7s_linear_infinite]',
      container: 'flex flex-col items-center',
      label: 'typography-body-9 mt-1.5',
    },
    variants: {
      size: {
        xsmall: { base: 'size-2' },
        small: { base: 'size-3' },
        medium: { base: 'size-4' },
        large: { base: 'size-15' },
        xlarge: { base: 'size-15' },
      },
      color: {
        muted: 'text-surface-muted',
        'muted-vivid': 'text-surface-muted-vivid',
        'muted-strong': 'text-surface-muted-strong',
        'muted-mild': 'text-surface-muted-mild',
        'muted-soft': 'text-surface-muted-soft',
        'muted-pale': 'text-surface-muted-pale',
        'muted-faint': 'text-surface-muted-faint',
        'white-pale': 'text-background-white-pale',
        'white-faint': 'text-background-white-faint',
        mono: 'text-surface-mono',
        primary: 'text-surface-primary',
        'primary-faint': 'text-surface-primary-faint',
        hero: 'text-surface-hero',
        'hero-faint': 'text-surface-hero-faint',
        pop: 'text-surface-pop',
        'pop-faint': 'text-surface-pop-faint',
        holler: 'text-surface-holler',
        'holler-faint': 'text-surface-holler-faint',
        sing: 'text-surface-sing',
        'sing-faint': 'text-surface-sing-faint',
        dance: 'text-surface-dance',
        'dance-faint': 'text-surface-dance-faint',
        success: 'text-surface-success',
        'success-faint': 'text-surface-success-faint',
        info: 'text-surface-info',
        'info-faint': 'text-surface-info-faint',
        warning: 'text-surface-warning',
        'warning-faint': 'text-surface-warning-faint',
        danger: 'text-surface-danger',
        'danger-faint': 'text-surface-danger-faint',
        'system-error': 'text-surface-system-error',
        'system-error-dark': 'text-surface-system-error-dark',
      },
    },
  },
  { responsiveVariants: ['xsl', 'sm', 'md', 'lg', 'xl'] },
);
