// import { BrandKeyWithThemes, type ColorsKey } from '@westpac/ui/types';

// export const PRIMARY_COLORS: ColorsKey[] = [
//   'background-pale',
//   'background-white',
//   'surface-muted',
//   'surface-muted-vivid',
//   'surface-muted-strong',
//   'surface-muted-mild',
//   'surface-muted-soft',
//   'surface-muted-pale',
//   'surface-muted-faint',
//   'surface-mono',
//   'surface-primary',
//   'surface-primary-faint',
//   'surface-hero',
//   'surface-hero-faint',
//   'surface-pop',
//   'surface-pop-faint',
//   'surface-holler',
//   'surface-holler-faint',
//   'surface-sing',
//   'surface-sing-faint',
//   'surface-dance',
//   'surface-dance-faint',
//   'surface-success',
//   'surface-success-faint',
//   'surface-info',
//   'surface-info-faint',
//   'surface-warning',
//   'surface-warning-faint',
//   'surface-danger',
//   'surface-danger-faint',
//   'surface-system-error',
//   'surface-system-error-dark',
//   'text-body',
//   'text-heading',
//   'text-muted',
//   'text-primary',
//   'text-hero',
//   'text-holler',
//   'text-link',
//   'text-success',
//   'text-info',
//   'text-warning',
//   'text-danger',
//   'text-system-error',
//   'text-mono',
//   'border-muted',
//   'border-muted-strong',
//   'border-muted-mild',
//   'border-muted-soft',
//   'border-hero',
//   'border-primary',
//   'border-pop',
//   'border-holler',
//   'border-sing',
//   'border-dance',
//   'border-success',
//   'border-success-mild',
//   'border-info',
//   'border-info-mild',
//   'border-warning',
//   'border-warning-mild',
//   'border-danger',
//   'border-danger-mild',
//   'border-mono',
//   'border-focus',
//   'data-a-solid',
//   'data-a-tint',
//   'data-a-opacity',
//   'data-b-solid',
//   'data-b-tint',
//   'data-b-opacity',
//   'data-c-solid',
//   'data-c-tint',
//   'data-c-opacity',
//   'data-d-solid',
//   'data-d-tint',
//   'data-d-opacity',
//   'data-e-solid',
//   'data-e-tint',
//   'data-e-opacity',
//   'data-f-solid',
//   'data-f-tint',
//   'data-f-opacity',
//   'surface-pictogram-base',
//   'surface-pictogram-accent',
//   'surface-hover-primary',
//   'surface-active-primary',
//   'surface-hover-hero',
//   'surface-active-hero',
//   'surface-hover-primary-faint',
//   'surface-active-primary-faint',
//   'surface-hover-hero-faint',
//   'surface-active-hero-faint',
//   'surface-hover-muted-pale',
//   'surface-active-muted-pale',
//   'surface-hover-mono',
//   'surface-active-mono',
// ];

// export const SECONDARY_COLORS: Record<BrandKeyWithThemes, Record<string, string>> = {
//   'wbc-light': {
//     'Bright Purple': '#991AD6',
//     'Bright Pink': '#FF3DDB',
//     'Dark Red': '#990000',
//     'Light Grey': '#E8E8ED',
//     'Light Purple': '#E0BAF2',
//     'Light Pink': '#FFD9F7',
//   },
//   'stg-light': {
//     Sky: '#3FC3EB',
//     Plum: '#502D79',
//     Amber: '#FF7F29',
//     'St.George Green': '#78BE20',
//     'St.George Yellow': '#FFCD00',
//   },
//   'bom-light': {
//     'Dark Purple': '#20024E',
//     'Mid Purple': '#685AC0',
//     'Light Purple': '#A094FC',
//   },
//   'btfg-light': {
//     'BT Blue': '#00AFD7',
//     'BT Black': '#2C2A29',
//     'BT Steel': '#80A1B6',
//   },
//   'bsa-light': {
//     Deep: '#00204F',
//     Bight: '#00ADBD',
//     Gum: '#5CBB3E',
//     Grape: '#A22269',
//     Sky: '#ABE2EC',
//     Outback: '#F7921E',
//   },
//   'wbc-dark': {
//     'Bright Purple': '#991AD6',
//     'Bright Pink': '#FF3DDB',
//     'Dark Red': '#990000',
//     'Light Grey': '#E8E8ED',
//     'Light Purple': '#E0BAF2',
//     'Light Pink': '#FFD9F7',
//   },
//   'stg-dark': {
//     Sky: '#3FC3EB',
//     Plum: '#502D79',
//     Amber: '#FF7F29',
//     'St.George Green': '#78BE20',
//     'St.George Yellow': '#FFCD00',
//   },
//   'bom-dark': {
//     'Dark Purple': '#20024E',
//     'Mid Purple': '#685AC0',
//     'Light Purple': '#A094FC',
//   },
//   'btfg-dark': {
//     'BT Blue': '#00AFD7',
//     'BT Black': '#2C2A29',
//     'BT Steel': '#80A1B6',
//   },
//   'bsa-dark': {
//     Deep: '#00204F',
//     Bight: '#00ADBD',
//     Gum: '#5CBB3E',
//     Grape: '#A22269',
//     Sky: '#ABE2EC',
//     Outback: '#F7921E',
//   },
// };

// export const ACCESSIBILITY_COLORS: ColorsKey[] = [];
