export function FontPreloader() {
  return (
    <>
      <link fetchPriority="low" rel="preload" href="/fonts/Aller_Bd.woff2" as="font" type="font/woff2" crossOrigin="" />
      <link fetchPriority="low" rel="preload" href="/fonts/Aller_Lt.woff2" as="font" type="font/woff2" crossOrigin="" />
      <link
        fetchPriority="low"
        rel="preload"
        href="/fonts/dragonbold-bold-webfont.woff2"
        as="font"
        type="font/woff2"
        crossOrigin=""
      />
      <link
        fetchPriority="low"
        rel="preload"
        href="/fonts/lineto-brown-pro-bold.woff2"
        as="font"
        type="font/woff2"
        crossOrigin=""
      />
      <link
        fetchPriority="low"
        rel="preload"
        href="/fonts/lineto-brown-pro-light.woff2"
        as="font"
        type="font/woff2"
        crossOrigin=""
      />
      <link
        fetchPriority="low"
        rel="preload"
        href="/fonts/lineto-brown-pro-regular.woff2"
        as="font"
        type="font/woff2"
        crossOrigin=""
      />
      <link
        fetchPriority="low"
        rel="preload"
        href="/fonts/montserrat-v14-latin-300.woff2"
        as="font"
        type="font/woff2"
        crossOrigin=""
      />
      <link
        fetchPriority="low"
        rel="preload"
        href="/fonts/montserrat-v14-latin-700.woff2"
        as="font"
        type="font/woff2"
        crossOrigin=""
      />
      <link
        fetchPriority="low"
        rel="preload"
        href="/fonts/montserrat-v14-latin-regular.woff2"
        as="font"
        type="font/woff2"
        crossOrigin=""
      />
      <link
        fetchPriority="low"
        rel="preload"
        href="/fonts/source-sans-pro-v14-latin-600.woff2"
        as="font"
        type="font/woff2"
        crossOrigin=""
      />
      <link
        fetchPriority="low"
        rel="preload"
        href="/fonts/source-sans-pro-v14-latin-700.woff2"
        as="font"
        type="font/woff2"
        crossOrigin=""
      />
      <link
        fetchPriority="low"
        rel="preload"
        href="/fonts/source-sans-pro-v14-latin-regular.woff2"
        as="font"
        type="font/woff2"
        crossOrigin=""
      />
      <link
        fetchPriority="low"
        rel="preload"
        href="/fonts/Westpac-Bold-v2.007.woff2"
        as="font"
        type="font/woff2"
        crossOrigin=""
      />
    </>
  );
}
