name: Retrieve application
thumbnail: {}
image:
  src: >-
    https://res.cloudinary.com/westpac-gel/image/upload/v1695685156/clmzj5r5w001ivd8iadshc9c7.png
  height: 1080
  width: 1920
author: Digital Experience
