name: Retrieve application
thumbnail: {}
image:
  src: "https://www.westpac.com.au/content/dam/public/gel/images/originations-retrieve-application-hero.png\r"
  alt: Stylised illustration of the retrieve application pattern.
author: Digital Experience
