import Link from 'next/link';

export { DesktopComputerPictogram, DriversLicencePictogram } from '@westpac/ui/pictogram';

export { MastercardAcceptedSymbol, WBCLogo } from '@westpac/ui/symbol';

export { StaticCode } from '../static-code/index';

export { ComponentTitle } from '../document-renderer/component-title';

export {
  Badge,
  Button,
  Well,
  Alert,
  Breadcrumb,
  BreadcrumbItem,
  Input,
  Select,
  Textarea,
  Tabs,
  TabsPanel,
  Accordion,
  AccordionItem,
  RadioGroup,
  RadioGroupRadio,
  CheckboxGroup,
  CheckboxGroupCheckbox,
  ButtonGroup,
  ButtonGroupButton,
  Switch,
  ProgressBar,
  Link,
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableFooter,
  TableHeader,
  TableHeaderCell,
  TableHeaderRow,
  TableRow,
  Collapsible,
  DatePicker,
  List,
  ListItem,
  ErrorMessage,
  FlexiCell,
  FlexiCellBody,
  FlexiCellFooter,
  FlexiCellAdornment,
  FlexiCellHint,
  FlexiCellLabel,
  FlexiCellButton,
  FlexiCellCircle,
  Circle,
  Autocomplete,
  AutocompleteItem,
  Panel,
  PanelBody,
  PanelFooter,
  ButtonDropdown,
  ButtonDropdownHeading,
  InputGroup,
  Modal,
  ModalBody,
  ModalFooter,
  Field,
  ProgressRope,
  VisuallyHidden,
  Pagination,
  Popover,
  Repeater,
  SkipLink,
  Compacta,
  Form,
  FormGroup,
  FormLabel,
  FormHint,
  FormSection,
  FormChitChat,
  Selector,
  SelectorAdornment,
  SelectorBody,
  SelectorButton,
  SelectorCircle,
  SelectorFooter,
  SelectorHint,
  SelectorButtonOption,
  SelectorCheckbox,
  SelectorLabel,
  SelectorLink,
  SelectorRadio,
  Grid,
  GridItem,
  Heading,
  ProgressIndicator,
} from '@westpac/ui';

export * from '@westpac/ui/icon';

export { GiftPictogram } from '@westpac/ui/pictogram';
export { Link as NextLink };

export {
  IconSizesDemo,
  AutoAddressDemo,
  ManualAddress,
  InternationalAddress,
  ComplexAddressDemo,
  EmploymentAutocompletePattern,
  EmploymentSelectFullPattern,
  TaxFileNumberPattern,
} from './components/demos';
export { Hr, Body } from './components/utils';
