import { type Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Protoform',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="wbc">
      <body>
        <main className="m-auto flex min-h-screen max-w-[1923px] flex-col overscroll-y-none border border-y-0 border-border">
          {children}
        </main>
      </body>
    </html>
  );
}
