import { type Metadata } from 'next';
import './globals.css';

import { ContentWrapper } from '@/components/content-wrapper/content-wrapper';
import { CustomFooter } from '@/components/custom-footer/custom-footer';
import { CustomHeader } from '@/components/custom-header/custom-header';
import { SidebarContextProvider } from '@/components/sidebar/context';
import { Sidebar } from '@/components/sidebar/sidebar';

export const metadata: Metadata = {
  title: 'Protoform',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-brand="wbc">
      <body>
        <main className="border-border m-auto max-w-[1923px] overscroll-y-none border border-y-0">
          <SidebarContextProvider>
            <CustomHeader />
            <Sidebar />
            <ContentWrapper>{children}</ContentWrapper>
            <CustomFooter />
          </SidebarContextProvider>
        </main>
      </body>
    </html>
  );
}
