export const BREAKPOINT_CLASSES = {
  rowSpan: {
    initial: {
      1: 'row-span-1',
      2: 'row-span-2',
      3: 'row-span-3',
      4: 'row-span-4',
      5: 'row-span-5',
      6: 'row-span-6',
    },
    xsl: {
      1: 'xsl:row-span-1',
      2: 'xsl:row-span-2',
      3: 'xsl:row-span-3',
      4: 'xsl:row-span-4',
      5: 'xsl:row-span-5',
      6: 'xsl:row-span-6',
    },
    sm: {
      1: 'sm:row-span-1',
      2: 'sm:row-span-2',
      3: 'sm:row-span-3',
      4: 'sm:row-span-4',
      5: 'sm:row-span-5',
      6: 'sm:row-span-6',
    },
    md: {
      1: 'md:row-span-1',
      2: 'md:row-span-2',
      3: 'md:row-span-3',
      4: 'md:row-span-4',
      5: 'md:row-span-5',
      6: 'md:row-span-6',
    },
    lg: {
      1: 'lg:row-span-1',
      2: 'lg:row-span-2',
      3: 'lg:row-span-3',
      4: 'lg:row-span-4',
      5: 'lg:row-span-5',
      6: 'lg:row-span-6',
    },
    xl: {
      1: 'xl:row-span-1',
      2: 'xl:row-span-2',
      3: 'xl:row-span-3',
      4: 'xl:row-span-4',
      5: 'xl:row-span-5',
      6: 'xl:row-span-6',
    },
  },
  span: {
    initial: {
      1: 'col-span-1',
      2: 'col-span-2',
      3: 'col-span-3',
      4: 'col-span-4',
      5: 'col-span-5',
      6: 'col-span-6',
      7: 'col-span-7',
      8: 'col-span-8',
      9: 'col-span-9',
      10: 'col-span-10',
      11: 'col-span-11',
      12: 'col-span-12',
    },
    xsl: {
      1: 'xsl:col-span-1',
      2: 'xsl:col-span-2',
      3: 'xsl:col-span-3',
      4: 'xsl:col-span-4',
      5: 'xsl:col-span-5',
      6: 'xsl:col-span-6',
      7: 'xsl:col-span-7',
      8: 'xsl:col-span-8',
      9: 'xsl:col-span-9',
      10: 'xsl:col-span-10',
      11: 'xsl:col-span-11',
      12: 'xsl:col-span-12',
    },
    sm: {
      1: 'sm:col-span-1',
      2: 'sm:col-span-2',
      3: 'sm:col-span-3',
      4: 'sm:col-span-4',
      5: 'sm:col-span-5',
      6: 'sm:col-span-6',
      7: 'sm:col-span-7',
      8: 'sm:col-span-8',
      9: 'sm:col-span-9',
      10: 'sm:col-span-10',
      11: 'sm:col-span-11',
      12: 'sm:col-span-12',
    },
    md: {
      1: 'md:col-span-1',
      2: 'md:col-span-2',
      3: 'md:col-span-3',
      4: 'md:col-span-4',
      5: 'md:col-span-5',
      6: 'md:col-span-6',
      7: 'md:col-span-7',
      8: 'md:col-span-8',
      9: 'md:col-span-9',
      10: 'md:col-span-10',
      11: 'md:col-span-11',
      12: 'md:col-span-12',
    },
    lg: {
      1: 'lg:col-span-1',
      2: 'lg:col-span-2',
      3: 'lg:col-span-3',
      4: 'lg:col-span-4',
      5: 'lg:col-span-5',
      6: 'lg:col-span-6',
      7: 'lg:col-span-7',
      8: 'lg:col-span-8',
      9: 'lg:col-span-9',
      10: 'lg:col-span-10',
      11: 'lg:col-span-11',
      12: 'lg:col-span-12',
    },
    xl: {
      1: 'xl:col-span-1',
      2: 'xl:col-span-2',
      3: 'xl:col-span-3',
      4: 'xl:col-span-4',
      5: 'xl:col-span-5',
      6: 'xl:col-span-6',
      7: 'xl:col-span-7',
      8: 'xl:col-span-8',
      9: 'xl:col-span-9',
      10: 'xl:col-span-10',
      11: 'xl:col-span-11',
      12: 'xl:col-span-12',
    },
  },
  start: {
    initial: {
      1: 'col-start-1',
      2: 'col-start-2',
      3: 'col-start-3',
      4: 'col-start-4',
      5: 'col-start-5',
      6: 'col-start-6',
      7: 'col-start-7',
      8: 'col-start-8',
      9: 'col-start-9',
      10: 'col-start-10',
      11: 'col-start-11',
      12: 'col-start-12',
      auto: 'col-start-auto',
    },
    xsl: {
      1: 'xsl:col-start-1',
      2: 'xsl:col-start-2',
      3: 'xsl:col-start-3',
      4: 'xsl:col-start-4',
      5: 'xsl:col-start-5',
      6: 'xsl:col-start-6',
      7: 'xsl:col-start-7',
      8: 'xsl:col-start-8',
      9: 'xsl:col-start-9',
      10: 'xsl:col-start-10',
      11: 'xsl:col-start-11',
      12: 'xsl:col-start-12',
      auto: 'xsl:col-start-auto',
    },
    sm: {
      1: 'sm:col-start-1',
      2: 'sm:col-start-2',
      3: 'sm:col-start-3',
      4: 'sm:col-start-4',
      5: 'sm:col-start-5',
      6: 'sm:col-start-6',
      7: 'sm:col-start-7',
      8: 'sm:col-start-8',
      9: 'sm:col-start-9',
      10: 'sm:col-start-10',
      11: 'sm:col-start-11',
      12: 'sm:col-start-12',
      auto: 'sm:col-start-auto',
    },
    md: {
      1: 'md:col-start-1',
      2: 'md:col-start-2',
      3: 'md:col-start-3',
      4: 'md:col-start-4',
      5: 'md:col-start-5',
      6: 'md:col-start-6',
      7: 'md:col-start-7',
      8: 'md:col-start-8',
      9: 'md:col-start-9',
      10: 'md:col-start-10',
      11: 'md:col-start-11',
      12: 'md:col-start-12',
      auto: 'md:col-start-auto',
    },
    lg: {
      1: 'lg:col-start-1',
      2: 'lg:col-start-2',
      3: 'lg:col-start-3',
      4: 'lg:col-start-4',
      5: 'lg:col-start-5',
      6: 'lg:col-start-6',
      7: 'lg:col-start-7',
      8: 'lg:col-start-8',
      9: 'lg:col-start-9',
      10: 'lg:col-start-10',
      11: 'lg:col-start-11',
      12: 'lg:col-start-12',
      auto: 'lg:col-start-auto',
    },
    xl: {
      1: 'xl:col-start-1',
      2: 'xl:col-start-2',
      3: 'xl:col-start-3',
      4: 'xl:col-start-4',
      5: 'xl:col-start-5',
      6: 'xl:col-start-6',
      7: 'xl:col-start-7',
      8: 'xl:col-start-8',
      9: 'xl:col-start-9',
      10: 'xl:col-start-10',
      11: 'xl:col-start-11',
      12: 'xl:col-start-12',
      auto: 'xl:col-start-auto',
    },
  },
} as const;
